# Numpy Exercise

#### 1. Import the numpy package under the name  (★☆☆)

In [3]:
import numpy as n


#### 2. Print the numpy version and the configuration  (★☆☆)

In [4]:
print(n.__version__)

1.17.2


#### 3. Create a null vector of size 10 (★☆☆)

In [6]:
n.zeros(10,dtype="int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### 4.  How to find the memory size of any array (★☆☆)

In [10]:
l=n.zeros(10,dtype="int")
print(l.size)
print(l.itemsize)
print(l.size*l.itemsize)

10
8
80


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [11]:
n.add?

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [12]:
x=n.zeros(10,dtype="int")
x[4]=1
print(x)

[0 0 0 0 1 0 0 0 0 0]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [13]:
n.array(range(10,50))

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [15]:
n.array([1,2,3])[::-1]


array([3, 2, 1])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [17]:
x=n.array(range(0,9))
print(x.reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [20]:
x=n.array([1,2,0,0,4,0])
n.nonzero(x)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [21]:
n.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [22]:
n.random.random((3,3,3))

array([[[0.53399579, 0.27705288, 0.1700662 ],
        [0.98071679, 0.65339871, 0.49387144],
        [0.83923251, 0.46774264, 0.9649104 ]],

       [[0.70001572, 0.62633608, 0.80464659],
        [0.03279754, 0.19638689, 0.9645091 ],
        [0.96165124, 0.25034032, 0.89931118]],

       [[0.10915593, 0.72987808, 0.9477064 ],
        [0.42130795, 0.92910207, 0.23144155],
        [0.04644043, 0.82069253, 0.92462926]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [26]:
x=n.random.random((10,10))
print(x.min(),x.max())

0.0005078320499714017 0.9975467585242219


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [28]:
x=n.random.random(30)
print(x.mean())

0.39379838011733365


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [33]:
x=n.ones((5,5),dtype="int")
x[1:-1,1:-1]=0
print(x)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [48]:
x=n.ones((5,5),dtype="int")
n.pad(x,pad_width=1,mode="constant",constant_values="0")

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0]])

#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [55]:
print(0*n.nan)
print(n.nan==n.nan)
print(n.inf>n.nan)
print(n.nan-n.nan)
print(n.nan in set([n.nan]))
print(.3==3*.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [59]:
n.diag(1+n.arange(4),k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [64]:
x=n.zeros((8,8),dtype="int")
x[::2,1::2]=1
x[1::2,::2]=1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [66]:
n.unravel_index(100,(6,7,8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [68]:
x=n.array([[0,1],[1,0]])
n.tile(x,(4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [73]:
x=n.random.random((5,5))
x_max,x_min=x.max(),x.min()
x=x-x_min/x_max-x_min
print(x)

[[ 0.71349078  0.34635332  0.60629032 -0.00517653  0.4650753 ]
 [ 0.86860229  0.50830296  0.68930512  0.33824768  0.64520737]
 [ 0.09279693  0.29735223  0.41848265  0.48427691 -0.02378816]
 [ 0.12800809  0.33459101  0.8323412   0.22482077 -0.02528096]
 [ 0.9459625   0.58558029  0.34297988  0.36333966  0.42338269]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [75]:
n.ubyte?



#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [76]:
n.dot(n.ones((5,3)),n.ones((3,2)))

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [83]:
x = n.arange(11)
x[(3 < x) & (x < 8)] *= -1
print(x)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [84]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))


9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [96]:
valid:
    z**z
    2<<z>>2
    z<-z
    z/1/1


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [101]:
n.array([n.nan]).astype(int).astype(float)

array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

In [109]:

n.intersect1d(n.random.randint(0,10,10),n.random.randint(0,10,10))



array([2, 4, 7])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [113]:
n.seterr(all="ignore")

{'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'}

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [115]:
n.sqrt(-1) == n.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [122]:
print(n.datetime64("today")-n.timedelta64("1"))
print(n.datetime64("today"))
print(n.datetime64("today")+n.timedelta64("1"))

2020-03-01
2020-03-02
2020-03-03


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [125]:
n.arange("2016-07","2016-08",dtype="datetime64[D]")

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [127]:
a=n.ones(5)
b=n.ones(5)*2
c=n.ones(5)*3
n.add(a,b,out=b)
n.divide(a,2,out=a)
n.negative(a,out=a)
n.multiply(b,a,out=a)
print(a)

[-1.5 -1.5 -1.5 -1.5 -1.5]


#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [140]:
z=n.random.uniform(0,10,10)
print(n.floor(z))
print(z.astype("int"))
print(n.ceil(z)-1)


[1. 0. 3. 6. 5. 0. 7. 1. 1. 8.]
[1 0 3 6 5 0 7 1 1 8]
[1. 0. 3. 6. 5. 0. 7. 1. 1. 8.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [143]:
z=n.zeros((5,5))
z+=n.arange(5)
print(z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

###39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [155]:
n.linspace(0,1,10)[1:-1]

array([0.11111111, 0.22222222, 0.33333333, 0.44444444, 0.55555556,
       0.66666667, 0.77777778, 0.88888889])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [151]:
z=n.random.uniform(0,10,10).astype("int")
z.sort()
print(z)

[0 0 3 4 4 4 7 7 8 9]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [161]:
z=n.arange(10)
n.sum(z)
n.add.reduce(z)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [163]:
a=n.arange(10)
b=n.arange(10)
print(n.array_equal(a,b))

True


#### 43. Make an array immutable (read-only) (★★☆)

In [31]:
a = n.arange(10)
a.flags.writeable = False
a[0] = 1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [43]:
import numpy as n
z=n.random.random((10,2))
x,y=z[:,0],z[:,1]
magnitudes=n.sqrt(x**2+y**2)
phases=n.arctan2(y,x)
print(magnitudes)
print(phases)

[0.85104055 0.9142991  0.99535087 1.09077956 0.72995609 0.72601666
 0.7285526  0.78115555 0.6184471  0.84515592]
[0.51217462 0.48715809 0.04961551 0.68502056 0.99768552 1.15480159
 0.37436484 1.3847142  0.92287694 0.57839631]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [171]:
z=n.random.randint(0,10,10)
print(z)
z[z.argmax()]=0
print(z)

[5 2 7 5 1 5 0 9 8 4]
[5 2 7 5 1 5 0 0 8 4]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [33]:
for i in [n.int8,n.int16,n.int64]:
    print(n.iinfo(i).min)
    print(n.iinfo(i).max)
for j in [n.float32,n.float16]:
    print(n.finfo(j).min)
    print(n.finfo(j).max)

-128
127
-32768
32767
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
-65500.0
65500.0


#### 49. How to print all the values of an array? (★★☆)

In [175]:

Z = n.zeros((16,16))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [48]:
scalar=n.random.uniform(0,100)
vector=n.arange(100)
print(n.abs(vector-scalar).argmin())
vector[n.abs(vector-scalar).argmin()]

56


56

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [58]:
z=n.random.randint(0,100,(100,2))
print(z)
x,y=n.atleast_2d(z[:,0],z[:,1])
n.sqrt((x-x.T)**2+(y-y.T)**2)

[[ 2 53]
 [23 99]
 [57  5]
 [30 65]
 [63 24]
 [12  8]
 [17 50]
 [79 42]
 [12 88]
 [77 44]
 [23 93]
 [81 44]
 [63 70]
 [ 6 48]
 [62 52]
 [64 49]
 [11 32]
 [84 69]
 [72 12]
 [41 14]
 [78 54]
 [35 94]
 [14 67]
 [70 90]
 [93 50]
 [19 63]
 [50 69]
 [68 89]
 [86 11]
 [38 51]
 [46 34]
 [18 10]
 [88 67]
 [75 77]
 [ 2 43]
 [31 93]
 [65 45]
 [39 70]
 [10 94]
 [60  7]
 [14 78]
 [59 76]
 [75 73]
 [35 98]
 [ 1 58]
 [92 23]
 [33 88]
 [72 93]
 [70 65]
 [79 48]
 [23 91]
 [43 81]
 [13 11]
 [60 43]
 [53 21]
 [56 96]
 [59 62]
 [51 21]
 [85 99]
 [25  1]
 [25 22]
 [53 16]
 [ 6 64]
 [53 71]
 [ 0 96]
 [49 64]
 [48 58]
 [ 5 11]
 [62 10]
 [94 12]
 [87 26]
 [24 68]
 [20 53]
 [90 91]
 [86 75]
 [ 2 98]
 [58 83]
 [96 60]
 [66 54]
 [55 45]
 [74 49]
 [34 64]
 [19 70]
 [ 2 58]
 [65 99]
 [90  7]
 [31 20]
 [99 87]
 [60 84]
 [94 77]
 [65 12]
 [89  5]
 [97 29]
 [43 91]
 [21 65]
 [76 20]
 [22 69]
 [ 8  4]
 [35 42]
 [24 10]]


array([[ 0.        , 50.56678752, 73.        , ..., 49.36598019,
        34.78505426, 48.3011387 ],
       [50.56678752,  0.        , 99.959992  , ..., 96.17692031,
        58.24946352, 89.0056178 ],
       [73.        , 99.959992  ,  0.        , ..., 49.01020302,
        43.0464865 , 33.37663854],
       ...,
       [49.36598019, 96.17692031, 49.01020302, ...,  0.        ,
        46.61544808, 17.08800749],
       [34.78505426, 58.24946352, 43.0464865 , ..., 46.61544808,
         0.        , 33.83784863],
       [48.3011387 , 89.0056178 , 33.37663854, ..., 17.08800749,
        33.83784863,  0.        ]])

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [67]:
z=(n.random.rand(10)*100).astype(n.float32)
y=z.view(n.int32)
y[:]=z
print(y)

[1108951173 1092098612 1114429781 1101767552 1114656040 1110203494
 1035415271 1085132891 1119510134 1107204062]


#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [41]:
import numpy as np
from io import StringIO
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [8]:
d=n.arange(9).reshape(3,3)
for i,j in n.ndenumerate(d):
    print(i,j)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [39]:
import numpy as n
z = 10
p = 3
Z = n.zeros((z,z))
n.put(Z, n.random.choice(range(z*z), p, replace=False),1)
print(Z)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [183]:
z=n.random.rand(5,10)
y=z-z.mean(axis=1).reshape(5,1)
t=z-z.mean(axis=1,keepdims=True)
print(y)
print(t)

[[-0.16160689 -0.1147148  -0.00807568 -0.32859599  0.09553849 -0.06227725
   0.37067366  0.02584416  0.51665635 -0.33344204]
 [ 0.00396705 -0.19789291  0.27140881  0.43451357  0.33334802 -0.3669746
  -0.15051403 -0.18622844 -0.19795764  0.05633017]
 [ 0.10696183  0.19208806  0.18200126 -0.49507978  0.06906745  0.32647917
  -0.16336045  0.09519614  0.20373684 -0.51709052]
 [ 0.27961081 -0.28598216 -0.20384405  0.45503731  0.34067216 -0.49983645
   0.31468094 -0.41478076  0.0634036  -0.04896141]
 [ 0.30620169 -0.51686012  0.14703341  0.08977818 -0.21579273  0.2777418
   0.10568348 -0.08775037  0.28615862 -0.39219396]]
[[-0.16160689 -0.1147148  -0.00807568 -0.32859599  0.09553849 -0.06227725
   0.37067366  0.02584416  0.51665635 -0.33344204]
 [ 0.00396705 -0.19789291  0.27140881  0.43451357  0.33334802 -0.3669746
  -0.15051403 -0.18622844 -0.19795764  0.05633017]
 [ 0.10696183  0.19208806  0.18200126 -0.49507978  0.06906745  0.32647917
  -0.16336045  0.09519614  0.20373684 -0.51709052]
 [

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [97]:
z=n.random.randint(0,10,(3,3)).astype("float")
z[1][0]=0.0
z[1][1]=0.0
z[1][2]=0.0
print(z)
(~z.all(axis=0)).any()

[[2. 4. 0.]
 [0. 0. 0.]
 [8. 0. 0.]]


True

#### 61. Find the nearest value from a given value in an array (★★☆)

In [74]:
z=n.random.uniform(0,1,10)
z.flat?

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [26]:
import numpy as n
n.random.randint(0,10,(3,4,3,4)).sum(axis=(-2,-1))

array([[44, 36, 54, 42],
       [50, 48, 49, 47],
       [59, 44, 64, 49]])

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

In [24]:
import numpy as n
z=n.random.uniform(0,1,(5,5))
y=n.random.uniform(0,1,(5,5))
dot=n.dot(z,y)
g=n.diag(dot)
print(g)
n.sum(z*y.T,axis=1)

[1.17168445 1.79971792 0.76776082 1.69264481 1.66880554]


2

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [34]:
import numpy as n
z=n.arange(1,11)
zer=3
ans=n.zeros(len(z)+(len(z)-1)*zer)
ans[::zer+1]=z
print(ans)

[ 1.  0.  0.  0.  2.  0.  0.  0.  3.  0.  0.  0.  4.  0.  0.  0.  5.  0.
  0.  0.  6.  0.  0.  0.  7.  0.  0.  0.  8.  0.  0.  0.  9.  0.  0.  0.
 10.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

In [16]:
import numpy as n
z=n.arange(10).reshape(2,5)
print(z[[0,1]])
z[[0,1]]=z[[1,0]]


[[0 1 2 3 4]
 [5 6 7 8 9]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [7]:
import numpy as n
n.logical_not(n.random.randint(0,2,100))

array([False,  True, False, False,  True, False,  True, False, False,
       False,  True, False,  True,  True, False, False,  True,  True,
       False, False,  True,  True, False, False, False, False, False,
       False,  True, False,  True,  True,  True, False, False, False,
        True, False,  True, False, False,  True,  True, False,  True,
       False,  True,  True, False, False,  True, False,  True,  True,
       False,  True, False, False,  True,  True,  True,  True,  True,
        True,  True, False,  True, False, False, False, False,  True,
        True, False, False, False, False, False,  True, False,  True,
        True, False,  True,  True, False, False, False, False, False,
        True,  True,  True,  True,  True,  True,  True,  True, False,
       False])

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

#### 82. Compute a matrix rank (★★★)

In [29]:
import numpy as n
z=n.random.randint(0,10,(5,5))
n.linalg.matrix_rank(z)

5

#### 83. How to find the most frequent value in an array?

In [10]:
import numpy as n
z=n.random.randint(0,10,10)
print(z)
print(n.bincount(z).argmax())

[5 3 3 1 7 0 2 2 3 1]
3


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

In [10]:
x=n.arange(1000)
n.random.shuffle(x)
print(x[n.argsort(x)[-3:]])


[997 998 999]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [98]:
n.asarray?

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [30]:
z=n.random.rand(int(10e7))
z*

array([0.16616434, 0.16731492, 0.61535962, ..., 0.24715636, 0.09666297,
       0.11495833])

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [23]:
Z=n.random.randint(0,10,(10,3))
E = n.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)

[[5 5 3]
 [5 6 2]
 [6 3 9]
 [3 8 7]
 [0 1 6]
 [3 5 1]
 [0 9 5]
 [8 8 7]
 [2 0 8]
 [2 1 4]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [27]:
z=n.random.randint(0,5,(4,4))
print(z)
n.unique(z,axis=1)

[[4 3 3 2]
 [0 3 1 0]
 [1 2 1 2]
 [4 4 3 1]]
[4 4 3 2]


array([[2, 3, 3, 4],
       [0, 1, 3, 0],
       [2, 1, 2, 1],
       [1, 3, 4, 4]])

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)