# Numpy Exercise

#### 1. Import the numpy package under the name  (★☆☆)

In [3]:
import numpy as n


#### 2. Print the numpy version and the configuration  (★☆☆)

In [4]:
print(n.__version__)

1.17.2


#### 3. Create a null vector of size 10 (★☆☆)

In [6]:
n.zeros(10,dtype="int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### 4.  How to find the memory size of any array (★☆☆)

In [10]:
l=n.zeros(10,dtype="int")
print(l.size)
print(l.itemsize)
print(l.size*l.itemsize)

10
8
80


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [11]:
n.add?

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [12]:
x=n.zeros(10,dtype="int")
x[4]=1
print(x)

[0 0 0 0 1 0 0 0 0 0]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [13]:
n.array(range(10,50))

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [15]:
n.array([1,2,3])[::-1]


array([3, 2, 1])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [17]:
x=n.array(range(0,9))
print(x.reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [20]:
x=n.array([1,2,0,0,4,0])
n.nonzero(x)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [21]:
n.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [22]:
n.random.random((3,3,3))

array([[[0.53399579, 0.27705288, 0.1700662 ],
        [0.98071679, 0.65339871, 0.49387144],
        [0.83923251, 0.46774264, 0.9649104 ]],

       [[0.70001572, 0.62633608, 0.80464659],
        [0.03279754, 0.19638689, 0.9645091 ],
        [0.96165124, 0.25034032, 0.89931118]],

       [[0.10915593, 0.72987808, 0.9477064 ],
        [0.42130795, 0.92910207, 0.23144155],
        [0.04644043, 0.82069253, 0.92462926]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [26]:
x=n.random.random((10,10))
print(x.min(),x.max())

0.0005078320499714017 0.9975467585242219


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [28]:
x=n.random.random(30)
print(x.mean())

0.39379838011733365


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [33]:
x=n.ones((5,5),dtype="int")
x[1:-1,1:-1]=0
print(x)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [48]:
x=n.ones((5,5),dtype="int")
n.pad(x,pad_width=1,mode="constant",constant_values="0")

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0]])

#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [55]:
print(0*n.nan)
print(n.nan==n.nan)
print(n.inf>n.nan)
print(n.nan-n.nan)
print(n.nan in set([n.nan]))
print(.3==3*.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [59]:
n.diag(1+n.arange(4),k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [64]:
x=n.zeros((8,8),dtype="int")
x[::2,1::2]=1
x[1::2,::2]=1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [66]:
n.unravel_index(100,(6,7,8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [68]:
x=n.array([[0,1],[1,0]])
n.tile(x,(4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [73]:
x=n.random.random((5,5))
x_max,x_min=x.max(),x.min()
x=x-x_min/x_max-x_min
print(x)

[[ 0.71349078  0.34635332  0.60629032 -0.00517653  0.4650753 ]
 [ 0.86860229  0.50830296  0.68930512  0.33824768  0.64520737]
 [ 0.09279693  0.29735223  0.41848265  0.48427691 -0.02378816]
 [ 0.12800809  0.33459101  0.8323412   0.22482077 -0.02528096]
 [ 0.9459625   0.58558029  0.34297988  0.36333966  0.42338269]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [75]:
n.ubyte?



#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [76]:
n.dot(n.ones((5,3)),n.ones((3,2)))

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [83]:
x = n.arange(11)
x[(3 < x) & (x < 8)] *= -1
print(x)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [84]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))


9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [96]:
valid:
    z**z
    2<<z>>2
    z<-z
    z/1/1


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [101]:
n.array([n.nan]).astype(int).astype(float)

array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

In [109]:

n.intersect1d(n.random.randint(0,10,10),n.random.randint(0,10,10))



array([2, 4, 7])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [113]:
n.seterr(all="ignore")

{'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'}

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [115]:
n.sqrt(-1) == n.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [122]:
print(n.datetime64("today")-n.timedelta64("1"))
print(n.datetime64("today"))
print(n.datetime64("today")+n.timedelta64("1"))

2020-03-01
2020-03-02
2020-03-03


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [125]:
n.arange("2016-07","2016-08",dtype="datetime64[D]")

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [127]:
a=n.ones(5)
b=n.ones(5)*2
c=n.ones(5)*3
n.add(a,b,out=b)
n.divide(a,2,out=a)
n.negative(a,out=a)
n.multiply(b,a,out=a)
print(a)

[-1.5 -1.5 -1.5 -1.5 -1.5]


#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [140]:
z=n.random.uniform(0,10,10)
print(n.floor(z))
print(z.astype("int"))
print(n.ceil(z)-1)


[1. 0. 3. 6. 5. 0. 7. 1. 1. 8.]
[1 0 3 6 5 0 7 1 1 8]
[1. 0. 3. 6. 5. 0. 7. 1. 1. 8.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [143]:
z=n.zeros((5,5))
z+=n.arange(5)
print(z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

###39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [155]:
n.linspace(0,1,10)[1:-1]

array([0.11111111, 0.22222222, 0.33333333, 0.44444444, 0.55555556,
       0.66666667, 0.77777778, 0.88888889])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [151]:
z=n.random.uniform(0,10,10).astype("int")
z.sort()
print(z)

[0 0 3 4 4 4 7 7 8 9]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [161]:
z=n.arange(10)
n.sum(z)
n.add.reduce(z)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [163]:
a=n.arange(10)
b=n.arange(10)
print(n.array_equal(a,b))

True


#### 43. Make an array immutable (read-only) (★★☆)

In [31]:
a = n.arange(10)
a.flags.writeable = False
a[0] = 1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [170]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[7 2 4 7 6 2 2 9 2 4]
[7 2 4 7 6 2 2 0 2 4]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [171]:
z=n.random.randint(0,10,10)
print(z)
z[z.argmax()]=0
print(z)

[5 2 7 5 1 5 0 9 8 4]
[5 2 7 5 1 5 0 0 8 4]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

In [ ]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [33]:
for i in [n.int8,n.int16,n.int64]:
    print(n.iinfo(i).min)
    print(n.iinfo(i).max)
for j in [n.float32,n.float16]:
    print(n.finfo(j).min)
    print(n.finfo(j).max)

-128
127
-32768
32767
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
-65500.0
65500.0


#### 49. How to print all the values of an array? (★★☆)

In [175]:

Z = n.zeros((16,16))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [48]:
scalar=n.random.uniform(0,100)
vector=n.arange(100)
print(n.abs(vector-scalar).argmin())
vector[n.abs(vector-scalar).argmin()]

56


56

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [ ]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [58]:
z=n.random.randint(0,100,(100,2))
print(z)
x,y=n.atleast_2d(z[:,0],z[:,1])
n.sqrt((x-x.T)**2+(y-y.T)**2)

[[ 2 53]
 [23 99]
 [57  5]
 [30 65]
 [63 24]
 [12  8]
 [17 50]
 [79 42]
 [12 88]
 [77 44]
 [23 93]
 [81 44]
 [63 70]
 [ 6 48]
 [62 52]
 [64 49]
 [11 32]
 [84 69]
 [72 12]
 [41 14]
 [78 54]
 [35 94]
 [14 67]
 [70 90]
 [93 50]
 [19 63]
 [50 69]
 [68 89]
 [86 11]
 [38 51]
 [46 34]
 [18 10]
 [88 67]
 [75 77]
 [ 2 43]
 [31 93]
 [65 45]
 [39 70]
 [10 94]
 [60  7]
 [14 78]
 [59 76]
 [75 73]
 [35 98]
 [ 1 58]
 [92 23]
 [33 88]
 [72 93]
 [70 65]
 [79 48]
 [23 91]
 [43 81]
 [13 11]
 [60 43]
 [53 21]
 [56 96]
 [59 62]
 [51 21]
 [85 99]
 [25  1]
 [25 22]
 [53 16]
 [ 6 64]
 [53 71]
 [ 0 96]
 [49 64]
 [48 58]
 [ 5 11]
 [62 10]
 [94 12]
 [87 26]
 [24 68]
 [20 53]
 [90 91]
 [86 75]
 [ 2 98]
 [58 83]
 [96 60]
 [66 54]
 [55 45]
 [74 49]
 [34 64]
 [19 70]
 [ 2 58]
 [65 99]
 [90  7]
 [31 20]
 [99 87]
 [60 84]
 [94 77]
 [65 12]
 [89  5]
 [97 29]
 [43 91]
 [21 65]
 [76 20]
 [22 69]
 [ 8  4]
 [35 42]
 [24 10]]


array([[ 0.        , 50.56678752, 73.        , ..., 49.36598019,
        34.78505426, 48.3011387 ],
       [50.56678752,  0.        , 99.959992  , ..., 96.17692031,
        58.24946352, 89.0056178 ],
       [73.        , 99.959992  ,  0.        , ..., 49.01020302,
        43.0464865 , 33.37663854],
       ...,
       [49.36598019, 96.17692031, 49.01020302, ...,  0.        ,
        46.61544808, 17.08800749],
       [34.78505426, 58.24946352, 43.0464865 , ..., 46.61544808,
         0.        , 33.83784863],
       [48.3011387 , 89.0056178 , 33.37663854, ..., 17.08800749,
        33.83784863,  0.        ]])

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [67]:
z=(n.random.rand(10)*100).astype(n.float32)
y=z.view(n.int32)
y[:]=z
print(y)

[1108951173 1092098612 1114429781 1101767552 1114656040 1110203494
 1035415271 1085132891 1119510134 1107204062]


#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from io import StringIO
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [8]:
d=n.arange(9).reshape(3,3)
for i,j in n.ndenumerate(d):
    print(i,j)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [ ]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [6]:
import numpy as np
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [8]:
import numpy as np
X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)

print(Y)

[[ 0.0806133   0.34760428 -0.43722171  0.31201067 -0.49863412 -0.09523134
   0.04958256  0.30598091 -0.3201236   0.25541904]
 [-0.08970068  0.325028   -0.12365651 -0.28378092  0.1144018  -0.28914754
  -0.29606463  0.13587514  0.4739866   0.03305874]
 [ 0.21006976  0.09095718 -0.27192904 -0.21264733  0.13305962  0.55262077
   0.11387059 -0.03383636 -0.23984725 -0.34231794]
 [ 0.14602094 -0.08724279  0.32875407 -0.10178522  0.02594868  0.32483979
  -0.27242822  0.29537504 -0.51074122 -0.14874109]
 [ 0.01423007 -0.47856358  0.43406692 -0.21792199  0.10440163 -0.01905311
   0.46637234 -0.18099395 -0.35682093  0.23428259]]


#### 59. How to sort an array by the nth column? (★★☆)

In [ ]:


Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [97]:
z=n.random.randint(0,10,(3,3)).astype("float")
z[1][0]=0.0
z[1][1]=0.0
z[1][2]=0.0
print(z)
(~z.all(axis=0)).any()

[[2. 4. 0.]
 [0. 0. 0.]
 [8. 0. 0.]]


True

#### 61. Find the nearest value from a given value in an array (★★☆)

In [74]:
z=n.random.uniform(0,1,10)
z.flat?

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [ ]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

#### 63. Create an array class that has a name attribute (★★☆)

In [9]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [ ]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [10]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

In [ ]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(np.unique(I))

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [ ]:
A = np.random.randint(0,10,(3,4,3,4))

sum = A.sum(axis=(-2,-1))
print(sum)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [ ]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

# Pandas solution as a reference due to more intuitive code
import pandas as pd
print(pd.Series(D).groupby(S).mean())

#### 69. How to get the diagonal of a dot product? (★★★)

In [ ]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version  
np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

NameError: name 'stride_tricks' is not defined

#### 82. Compute a matrix rank (★★★)

In [ ]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

#### 83. How to find the most frequent value in an array?

In [10]:
import numpy as n
z=n.random.randint(0,10,10)
print(z)
print(n.bincount(z).argmax())

[5 3 3 1 7 0 2 2 3 1]
3


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [ ]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

In [10]:
x=n.arange(1000)
n.random.shuffle(x)
print(x[n.argsort(x)[-3:]])


[997 998 999]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [3]:
import numpy as np
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [ ]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [30]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

array([0.16616434, 0.16731492, 0.61535962, ..., 0.24715636, 0.09666297,
       0.11495833])

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [ ]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [23]:
Z=n.random.randint(0,10,(10,3))
E = n.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)

[[5 5 3]
 [5 6 2]
 [6 3 9]
 [3 8 7]
 [0 1 6]
 [3 5 1]
 [0 9 5]
 [8 8 7]
 [2 0 8]
 [2 1 4]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [ ]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

# Author: Daniel T. McDonald

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [27]:
z=n.random.randint(0,5,(4,4))
print(z)
n.unique(z,axis=1)

[[4 3 3 2]
 [0 3 1 0]
 [1 2 1 2]
 [4 4 3 1]]
[4 4 3 2]


array([[2, 3, 3, 4],
       [0, 1, 3, 0],
       [2, 1, 2, 1],
       [1, 3, 4, 4]])

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)